### ISSUE TITLE
Is this what you use at salah.com

### ISSUE THREAD

**Issue by banago** [mmahalwy/prayertimes#1]
Salam alaykum @mmahalwy, 

Is this functionality what you use at salah.com?

**Comment by mmahalwy** [comment]
Salam @banago 

It is not. I don't work on Salah.com unfortunately.

**Comment by banago** [comment]
I thought you were involved because your sites are interlinked. Thanks.

**Comment by mmahalwy** [comment]
Nope, just quran.com!
